### ISSUE TITLE
[Help Request] New issues are not being created and CLI not output anything

### ISSUE THREAD

**Issue by thulioph** [JasonEtco/todo#133]
## Checklist

- [x] I already stalled the `todo-app` on my Github account.

- [x] I already updated the my [`config.yml`](https://github.com/thulioph/spotify-tips/blob/989e5b297933eb5596c9ee225c61fe8e55ce7df7/.github/config.yml) file.

- [x] I already added a [new comment](https://github.com/thulioph/spotify-tips/blob/989e5b297933eb5596c9ee225c61fe8e55ce7df7/src/index.js) on my codebase.

## Files

- Here is my console output, after running the command: http://showterm.io/487d6b0518a2fb5be67e2

- Here is my opened pull request: https://github.com/thulioph/spotify-tips/pull/16

## Questions

1. What could be the problem?

2. I try to use the CLI passing file, or the `commit SHA` and both don't work.

Thanks!

**Comment by JasonEtco** [comment]
I'm sorry, but I don't have the bandwidth to be able to help people on a 1-on-1 basis 😢 

It looks like you've installed the `todo` package - the CLI is part of this repo, so clone it and try that. I'm going to close this because I don't have time to help you - I suggest you dig into the code and try to figure out whats going wrong.
