### ISSUE TITLE
Notify if config breaks the code

### ISSUE THREAD

**Issue by zoispag** [JasonEtco/todo#161]
I uploaded a config with the following:

```yaml
todo:
  keyword: ["@todo", "TODO", "dump("]
```

I believe that the `(` broke the regex, since it was not escaped, but it took me a few commits and some time to figure it out.
I think it would be useful if it could open an issue / write a comment in the PR, if the config somehow breaks the todo app.

**Comment by JasonEtco** [comment]
Thanks for opening this @zoispag, and I'm sorry about the super long delay. This is a larger problem in Probot - here's [one discussion](https://github.com/probot/probot/issues/299), but there have been a few. Since this is outside of the scope of TODO and better left to Probot to handle, I'm going to close this issue - but it's still on my radar for improvements to the framework. Cheers!
