### ISSUE TITLE
Scan existing code

### ISSUE THREAD

**Issue by PatMyron** [JasonEtco/todo#164]
It'd be fantastic if Todo could scan existing code and open up issues for previously committed TODOs

**Comment by JasonEtco** [comment]
No arguments here - however, I don't think it has a huge impact, since it'd only act once per repo. The thing is, Todo's current implementation specifically acts on diffs - this is for performance mostly. So things would have to change a lot for that to be viable.

That said, I'm open to a PR getting this into Todo! It'd have to listen for `installation_repositories.added` events, and deal with the Gitdata tree and blob APIs.

**Comment by Kampfkarren** [comment]
Any update on this? It'd be extremely useful.

**Comment by Kampfkarren** [comment]
Then what, did you just manually make the issue?

**Comment by rugk** [comment]
yes

**Comment by rugk** [comment]
Yes, bot, it is. 🤖

**Comment by JasonEtco** [comment]
I'm not going to be able to add this capability - if anyones interested, a PR would be great, but I'm not sure that it fits within the scope of this app. I think a separate CLI would make more sense, or a total overhaul that reads the whole repo on-push (and that's not something I want to do in this repo). I hope that makes sense.

**Comment by rugk** [comment]
yeah, shh #badbot :no_bell::robot::no_bell:

**Comment by PatMyron** [comment]
I don't mind if this issue is closed as wontfix or left open and neglected indefinitely, but I'd prefer if a bot did not ask if the most +1'd issue is still relevant every couple months

**Comment by JasonEtco** [comment]
Yeah, not sure why it ignored the activity. But I'm inclined to leave it closed, because it's not something I can tackle, and because I don't think it's something that this app should be able to do. Due to how it scans for TODOs (via diffs), it'd be pretty hefty to instead scan all files; might be better for a GitHub Actions implementation of todo!
