### ISSUE TITLE
how many todos can it catch in the same file?

### ISSUE THREAD

**Issue by kguidonimartins** [JasonEtco/todo#173]
Hey there, thanks for this app! It's awesome!

I have some files with a lot of todos, but the bot seems that can catch only one in each file. Am I wrong?

**Comment by kguidonimartins** [comment]
There was a little lag, but it worked like a charm.

**Comment by JasonEtco** [comment]
Hey thanks for the note, and for closing the issue. I'm surprised it took _that long_, but it does take a bit of time to parse large diffs - especially those that have a number of TODOs. This is kind of intentional, to ensure that duplicate TODO comments/issues aren't generated (so we create one, then give it a hot second before checking if one by that name already exists).
