### ISSUE TITLE
[BUG] Missed todo creation when merging PR

### ISSUE THREAD

**Issue by roblabla** [JasonEtco/todo#186]
**Describe the bug**
When merging https://github.com/roblabla42/KFS/pull/157, an issue was not created for the TODO associated with it. I did some tests with the CLI (see PR #187), and it does detect the TODO properly:

```
roblabla@roblab ~/Dropbox/dev/src/js/todo master $ node bin/todo.js -o roblabla42 -r KFS --pr 157
Item found [Write some AHCI documentation] in [roblabla42/KFS] at [7d7fbcbf3c6409c357e00e30d5c18503203d8896]
Creating issue [Write some AHCI documentation] in [roblabla42/KFS]
---
Title: Write some AHCI documentation
Body:
 https://github.com/roblabla42/KFS/blob/7d7fbcbf3c6409c357e00e30d5c18503203d8896/ahci/src/main.rs#L1-L4

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 7d7fbcbf3c6409c357e00e30d5c18503203d8896 when #157 was merged. cc @roblabla.
---
```

**To Reproduce**
Unsure. Maybe I got unlucky and merged the PR while the bot was down?

**Expected behavior**
An issue should have been created.

**Comment by JasonEtco** [comment]
I'm assuming this was due to some downtime in the app - its been having trouble recently 😞 I'm going to close this, but you may still experience issues until I've figured out whats going on. In the meantime, you can [deploy your own app](https://github.com/JasonEtco/todo/blob/master/docs/deploy.md) - you may very well encounter the same runtime errors, in which case, PRs welcome 😭

**Comment by k1o0** [comment]
We recently installed the todo bot via GitHub Apps and also don't see any issues being created on merge:
https://github.com/cortex-lab/Rigbox/pull/119

Are issues only created when merging into master?  If so this could be added to the documentation.

**Comment by JasonEtco** [comment]
@k1o0 it appears that that PR's diff is too large: `136635/100000` (`your pr / the limit`). I instituted a limit to the size of diffs that would be parsed because overly large diffs (like people committing minified files) were causing downtime (see #194). Happy to raise that limit if needed, it was an arbitrary thing (I did some digging to find the average diff size internally). Can you open a new issue about it?
