### ISSUE TITLE
[BUG] Not creating issues in JS or python, in private or public repos

### ISSUE THREAD

**Issue by AmirAlavi** [JasonEtco/todo#188]
**Describe the bug**
I've installed this app in two of my repos, and have tried adding todo comments to no avail. It's just not making issues.

I've tried it in python with `# TODO`:
https://github.com/AmirAlavi/test-todo/commit/43b733ac124cdf2c39ec8f7a851f6acf2b8aa258

I've also tried in python with `@TODO`:
https://github.com/AmirAlavi/test-todo/commit/418407ee102f51fca5b6b9da08c608ee7e8928e7

Neither worked, so I though I should try a JS file:
https://github.com/AmirAlavi/test-todo/commit/0a8f23082a4f7d6c3e0a1c3967009743ded674ee

I also tried adding and removing the comments (see other commits in that repo)

I initially tried todo in my private repo (python code) and when I couldn't get that going no matter what, I created the above public repo to test it.

Is there something I'm missing?

**Comment by JasonEtco** [comment]
The deployed application has been having some problems recently that I haven't had a chance to dig into. For reference, here are some metrics for the last 24 hours:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/10660468/51585150-460a5f00-1ea6-11e9-94f3-861e7dd29e15.png">

This seems to be resulting in "downtime", which due to the nature of webhook-driven applications fails silently. For now, you'll either have to stick it out until I've figured out whats going on, or [deploy your own TODO](https://github.com/JasonEtco/todo/blob/master/docs/deploy.md) if you're really keen to try it.

**Comment by AmirAlavi** [comment]
@JasonEtco Thanks for the update and working on this app. I had recently discovered this great tool, and hadn't really integrated it into my workflow yet, so I can definitely wait. In the meantime, I've noticed you've closed all issues related to this downtime. Maybe there should be a single issue created to track this so that users can watch that issue and know that when it closes, things are back to normal? Right now, I'll have to keep re-trying todo to discover if it's working.

**Comment by JasonEtco** [comment]
Yeah, thanks for the suggestion @AmirAlavi.

**Comment by aawadall** [comment]
in case of python, since we have no support for block comment, how to define verbose issues in body?
does it have to be in the same line?

**Comment by JasonEtco** [comment]
@aawadall you can do the following as single lines:

```python
# TODO: Title
# BODY: A body
```

If you need more help, please open another issue ❤️
