### ISSUE TITLE
[BUG] C comment /**/ has trailing */

### ISSUE THREAD

**Issue by tjysdsg** [JasonEtco/todo#190]
**Describe the bug**
When the TODOs are in the following form:
```
/* TODO: xxx */
```
The issue generated by todobot is titled as:
```
 xxx */
```
instead of `xxx`

**To Reproduce**
1. Go to anywhere in the source file
2. Add comment `/* TODO */`
3. Commit and push
4. See the generated issue in the corresponding repo

**Expected behavior**
todobot generates the issue titled `xxx` without trailing `*/`
`

**Screenshots**
![todobot-issue](https://user-images.githubusercontent.com/21212505/52338760-3febb500-2a46-11e9-9795-f235304d6476.jpg)

**Comment by tjysdsg** [comment]
I understand that there are many ways to avoid this problem such as modifying the one-line comment to multi-line comment, or like changing the settings of todobot. But I believe as long as todobot supports `C`, it should handle this thing without bothering changing the source code. I almost know nothing about building Github bot or javascript, so I'd really appreciate it if anyone can help fix this!

**Comment by JasonEtco** [comment]
Hey @tjysdsg - thanks for opening this. Frankly, there's not a lot that can be done here without targeting these cases very specifically.

todo parses the diff as a string, not as a language AST - this is to be language agnostic. That means that it has no concept of comments: where they start _or end_. So, we can certainly say "if the title ends with `*/`, remove it" - but that may break other use cases where that's intentional and used in a different language. I'm open to discussing it, or just adding a `trimFromEnd` config or something.

**Comment by tjysdsg** [comment]
Got it, I'll just change my config for now.

**Comment by JasonEtco** [comment]
I'm going to close this for now @tjysdsg because there is nothing actionable, but if you're still interested in talking about a `trimFromEnd` config feel free to open another issue!
