### ISSUE TITLE
[BUG] Issues not being created when merging dev branch to master

### ISSUE THREAD

**Issue by jestarr** [JasonEtco/todo#237]
**Describe the bug**
Issues are not being created when I merge the dev branch to the master.  Originally I thought it was due to my dev branch merge being pretty sizable.  I created a test `TODO` and then merged that separately.

<img width="1021" alt="Screenshot 2019-11-14 05 30 36" src="https://user-images.githubusercontent.com/28405066/68849477-272cc180-06a0-11ea-8521-d61dc847bb68.png">

**Comment by JasonEtco** [comment]
Hi @jestarr - can you share your `.github/config.yml` file if you have one? And any more information about your repository, and possibly a link to the commit would be helpful!

**Comment by jestarr** [comment]
I don't have a `.github/config.yml` file.  It's a private repo for an R package that I built.  
![Capture](https://user-images.githubusercontent.com/28405066/68998856-bcd57600-0885-11ea-90a0-1c8d5c2dfda6.PNG)

I use the `dev` branch to do most of my work, and then `merge` to `master` for major changes.

**Comment by JasonEtco** [comment]
Thanks for that info @jestarr. Are you merging via a pull request, or just manually doing something like `git merge`? It matters because todo treats those very differently.

**Comment by jestarr** [comment]
I’m almost 100% sure I used a `git merge` To just merge the `dev` Into `master`

**Comment by JasonEtco** [comment]
Gotcha. Ok, so this is _expected_, but not _good_ - todo will ignore merge commits because the handling of merge-related things is typically done through PRs:

https://github.com/JasonEtco/todo/blob/e71c4905f5df8ef5120051798cae1010303c3b21/lib/push-handler.js#L16-L18

That said, I don't think that's the correct behavior. Ignoring merge commits _from a PR_ is correct, but merge commits outside of a PR should be treating like a regular commit. If you're interested in contributing, that'd look something like:

```js
  const commit = await context.github.git.getCommit(context.repo({commit_sha: context.payload.head_commit.id}))
  const isMergeCommit = commit.data.parents.length > 1
  if (isMergeCommit) {
    // Figure out if the commit is part of a pull request
    const isFromPr = true
    if (isFromPr) return
  }
```

Could likely leverage the GraphQL API's [`Commit.associatedPullRequests`](https://developer.github.com/v4/object/commit/#connections) connection, and maybe even save the first request.

**Comment by jestarr** [comment]
Sorry.  Not sure I follow what I should be doing to fix this?

**Comment by jestarr** [comment]
The issue is still relevant.  I wasn't sure how I could move it forward since I don't understand the directive given.  Can you explain?

**Comment by afcuttin** [comment]
Relevant to me, too :)
