### ISSUE TITLE
[BUG] NEED boundary check of TODO

### ISSUE THREAD

**Issue by marocchino** [JasonEtco/todo#241]
**Describe the bug**

It creates an issue unexpectedly.

**To Reproduce**

When I write a comment in javascript code.
```js
/*
 * OTODOKE_HOPE_TIME
 */
```

**Expected behavior**
It creates an issue because O`TODO`KE has `TODO`. but, I want to do nothing.

**Screenshots**
<img width="550" alt="Screen Shot 2020-01-09 at 14 53 52" src="https://user-images.githubusercontent.com/128431/72041822-e7750580-32ef-11ea-8b2a-5648694856e1.png">

**Additional context**

maybe need some boundary checks when we detecting TODO.

**Comment by JasonEtco** [comment]
Hi @marocchino 👋 thanks for opening this. I agree, it'd be a good addition; it's a little tricky, because the formatting of todo comments can be one of many things, including:

```
//TODO
// TODO
```

Where the `//T` may cause issues. That said, we should still handle it. If you're up for opening a PR, we'd want to make that change to this regular expression:
