### ISSUE TITLE
Bot is opening duplicate issues and not returning the proper snippets

### ISSUE THREAD

**Issue by mattstratton** [JasonEtco/todo#38]
For example on the incorrect snippets https://github.com/devopsdays/devopsdays-cli/issues/101

Looking at the issues on that same repo (I'm going to be closing them, but you can find them under closed) you can see that there are dupes. The first time around I thought it was because I had renamed the issues, but there are even some with the same.

**Comment by JasonEtco** [comment]
Hey @mattstratton, thanks for opening this up!

The duplicate issues shouldn't be a problem, I very recently made a change in how it detects existing issues of the same name. Now it sores metadata in the issue body and checks that rather than just the title. However, that change meant that it would dupe issues that did not have that metadata, ie whatever was there in the couple hours before the change was made.

There is a known issue with blobs where if the file is, for example, 10 lines long and the issue title is on the last line, it gets confused since there is no line 15 (the issue title plus the configed blobLines number).

Do those two things answer your question? I'll leave this open for the second part of it until it's fixed.

**Comment by mattstratton** [comment]
Aha...I see how that can happen. And especially in this case. I'll go ahead and close this.

Cool tool!

**Comment by JasonEtco** [comment]
Thanks 😁  I'll open up a separate issue for the blob lines part of your question, and I'm working on a fix as we speak 👍

**Comment by JasonEtco** [comment]
@mattstratton should be fixed by #40, just deployed the changes as well. Let me know in #39 if you're still seeing this problem!
