### ISSUE TITLE
keyword for various files

### ISSUE THREAD

**Issue by ignatandrei** [JasonEtco/todo#79]
For example, in C# we have
//TODO
Could this be added to default configuration?
Such as 
for .cs files: //TODO
for .js files: @todo

**Comment by JasonEtco** [comment]
That's a cool idea - I'm hesitant to try for format-specific configs, it'd be hard to keep track of all the different "standard" conventions per language. However, enabling an array of keywords is totally doable. Would you like to make a PR @ignatandrei?

**Comment by tigercosmos** [comment]
Maybe we can just support muilti-variable for keyword?

**Comment by JasonEtco** [comment]
@tigercosmos yep! I'd love to see you open a PR if you'd like 👍

**Comment by tigercosmos** [comment]
@JasonEtco  Could you point out where the related code is?

**Comment by JasonEtco** [comment]
Certainly @tigercosmos!

This bit handles the RegEx searching within file contents. You can check an array of strings instead of one string, but it should still support one keyword if the config is `typeof string`.

https://github.com/JasonEtco/todo/blob/11ef549fbdbf8819b1f267dfedd5c743568ba7f5/lib/open-issues.js#L43-L50

There is some similar code in the PR merge handler (should there be duplicate code? Absolutely not 😊):

https://github.com/JasonEtco/todo/blob/11ef549fbdbf8819b1f267dfedd5c743568ba7f5/lib/merge-handler.js#L39-L42

Let me know if you have any questions!

**Comment by JasonEtco** [comment]
@tigercosmos in #80 I added a new helper to scan files for keywords a bit more easily - I suggest you use that (the `searchContentsForTitles()` function).

**Comment by tigercosmos** [comment]
Ok thanks!

**Comment by bkeepers** [comment]
👍 for supporting more formats by default. It's very common in JavaScript to do `// TODO: …text…` as well.
