### ISSUE TITLE
Same label, not the same Issue

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#94]
I created two todos with the same name, tho they were in two different files (or even in 2 different part of the code) but the bot didn't create two issues, only one 😞

**Comment by JasonEtco** [comment]
In the check for duplicate issues, it previously also identified if a todo with the same name was in different files, and would create multiple issues accordingly. However, this created friction when people would move a todo from one file to another; it would create a new issue. I removed the same-file check, so now it _only_ checks if an issue with the same title exists.

Since I've made that change fairly recently, I'm going to wait it out and see if the change becomes a new source of friction. Thanks for letting me know!

**Comment by Seluj78** [comment]
Alright thanks for the explanation ! 👌
